keonmon/MealZo_final

- src/main/java/com/mealzo/controller/MQnaController.java
- src/main/java/com/mealzo/dao/IMQnaDao.java
- src/main/java/com/mealzo/dto/MQnaVO.java
- src/main/java/com/mealzo/service/MQnaService.java
- src/main/resources/mybatis/mapper/MQna.xml
- src/main/webapp/WEB-INF/views/index.jsp
> Qna 관련틀(Controller, service, dao, dto, xml)(신우진이함)

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/dao/IMMemberDao.java
- src/main/java/com/mealzo/dto/MMemberVO.java
- src/main/java/com/mealzo/service/MMemberService.java
- src/main/webapp/WEB-INF/views/index.jsp
- src/main/webapp/WEB-INF/views/member/login.jsp
> Member 관련 틀 (Controller, service, dto, dao mxl) - 강민지

- src/main/java/com/mealzo/dao/IMMemberDao.java
- src/main/java/com/mealzo/dao/IMQnaDao.java
- src/main/java/com/mealzo/service/MMemberService.java
- src/main/webapp/WEB-INF/views/include/user/headerfooter/header.jsp
> [건희] 220328 IMQnaDao 인터페이스로 수정, 로그인으로 이동 안하는 버그 수정

- src/main/java/com/mealzo/controller/MQnaController.java
- src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> MQna  마이페이지 이동

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/dao/IMMemberDao.java
- src/main/java/com/mealzo/dto/MMemberVO.java
- src/main/java/com/mealzo/service/MMemberService.java
- src/main/resources/mybatis/mapper/MMemberDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/member/login.jsp
> [성희] 220329 로그인/로그아웃

- src/main/java/com/mealzo/controller/MQnaController.java
- src/main/java/com/mealzo/dao/IMQnaDao.java
- src/main/java/com/mealzo/service/MQnaService.java
- src/main/resources/mybatis/mapper/MQna.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/include/user/mypage_sidemenu.jsp
- src/main/webapp/WEB-INF/views/qna/qnaList.jsp
> Q&A LIST 까지 ! 페이징 안함 아직

- src/main/java/com/mealzo/controller/MProductController.java
- src/main/java/com/mealzo/dao/IMProductDao.java
- src/main/java/com/mealzo/dto/AdminPaging.java
- src/main/java/com/mealzo/dto/Paging.java
- src/main/java/com/mealzo/dto/UserPaging.java
- src/main/java/com/mealzo/dto/UserPaging2.java
- src/main/java/com/mealzo/service/MProductService.java
- src/main/resources/mybatis/mapper/MProductDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/include/paging/paging.jsp
- src/main/webapp/WEB-INF/views/product/dummy.jsp
- src/main/webapp/WEB-INF/views/product/product.js
- src/main/webapp/WEB-INF/views/product/productAll.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
- src/main/webapp/WEB-INF/views/product/productNew.jsp
- src/main/webapp/WEB-INF/views/product/productkind.jsp
> [건희] 220329 전체메뉴 구현

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/MProductController.java
- src/main/resources/mybatis/mapper/MCartDao.xml
- src/main/webapp/WEB-INF/views/include/user/headerfooter/header.jsp
- src/main/webapp/WEB-INF/views/product/productkind.jsp
> [건희] pc로 작업파일 옮기기 위해 커밋

- src/main/java/com/mealzo/dto/Paging.java
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
Paging객체 Merge과정에서 오류가 있었습니다.
수정 후 다시 커밋합니다.
> [건희] ProductKind 버그 수정 후 커밋

- src/main/java/com/mealzo/controller/MProductController.java
- src/main/java/com/mealzo/dao/IMProductDao.java
- src/main/java/com/mealzo/dao/IMReviewDao.java
- src/main/java/com/mealzo/dto/Paging.java
- src/main/java/com/mealzo/service/MProductService.java
- src/main/java/com/mealzo/service/MReviewService.java
- src/main/resources/mybatis/mapper/MProductDao.xml
- src/main/resources/mybatis/mapper/MReviewDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/include/user/headerfooter/footer.jsp
- src/main/webapp/WEB-INF/views/include/user/headerfooter/header.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
리뷰 가져오는 기능도 있어서
MReviewService,
IMReivewDao,
MReviewDao.xml도 생성되었습니다.
> [건희] productDetail 구현 완료

- src/main/java/com/mealzo/controller/MAskController.java
- src/main/resources/mybatis/mapper/MAskDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/include/paging/productPaging.jsp
- src/main/webapp/WEB-INF/views/mypage/myAskWrite.jsp
- src/main/webapp/WEB-INF/views/product/productAll.jsp
- src/main/webapp/WEB-INF/views/product/productkind.jsp
- src/main/webapp/WEB-INF/views/sql.sql
> 페이징 & 상품문의 완료 & 프로덕트 페이징 추가 버그 찾음 ^^

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/java/com/mealzo/dao/IMOrderDao.java
- src/main/java/com/mealzo/service/MOrderService.java
- src/main/resources/mybatis/mapper/MCartDao.xml
- src/main/resources/mybatis/mapper/MOrderDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/include/user/headerfooter/header.jsp
- src/main/webapp/WEB-INF/views/include/user/mypage_sidemenu.jsp
- src/main/webapp/WEB-INF/views/order/orderDetail.jsp
- src/main/webapp/WEB-INF/views/order/orderList.jsp
장바구니 카트 dao.xml파일 수정,  멤버컨트롤러 수정, 오더리스트 추가
> 장바구니 카트 dao.xml파일 수정,  멤버컨트롤러 수정, 오더리스트 추가

- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
> [한성희] 220331 회원가입 프로시저 추가

- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
> 프로시져 추가입니다..

- src/main/resources/static/user/script/product.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
> 유저단 스크립트 수정

- src/main/java/com/mealzo/controller/MProductController.java
- src/main/java/com/mealzo/controller/MReviewController.java
- src/main/java/com/mealzo/dao/IMReviewDao.java
- src/main/java/com/mealzo/dto/MReviewVO.java
- src/main/java/com/mealzo/service/MMemberService.java
- src/main/java/com/mealzo/service/MReviewService.java
- src/main/resources/mybatis/mapper/MReviewDao.xml
- src/main/resources/static/user/css/meal.css
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/mypage/myReviewWrite.jsp
- src/main/webapp/WEB-INF/views/sql.sql
추가 문후 한번만 쓸수 있는 기회와 후기목록에 내가 산 후기 리뷰 작성하기 도 구현하기
> 리뷰쓰기 & 구매한 사람만 리뷰 쓰기 완료

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/dao/IMAdminDao.java
- src/main/java/com/mealzo/dto/MAskVO.java
- src/main/java/com/mealzo/service/MAdminService.java
- src/main/resources/mybatis/mapper/MAdminDao.xml
- src/main/resources/static/admin/script/adminProduct.js
- src/main/resources/static/user/css/meal.css
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/qna/askDetil.jsp
- src/main/webapp/WEB-INF/views/admin/qna/askList.jsp
- src/main/webapp/WEB-INF/views/admin/qna/reviewList.jsp
- src/main/webapp/WEB-INF/views/qna/qnaView.jsp
- src/main/webapp/WEB-INF/views/sql.sql
빈칸일 때 벨리드 안됨 자바스크립으로 수정할지 고민 ...ㅠㅠ
> 상품문의 답글 & 답글 수정 & 리스트 검색 &페이징 완료

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/dao/IMOrderDao.java
- src/main/java/com/mealzo/service/MOrderService.java
- src/main/resources/mybatis/mapper/MOrderDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/order/morderList.jsp
[건희] 1.주문배송정보 변경기능 구현  2. 주문/배송관리 변경 버튼위치 수정
> [건희] 1.주문배송정보 변경기능 구현  2. 주문/배송관리 변경 버튼위치 수정

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/dao/IMAdminDao.java
- src/main/java/com/mealzo/dto/MAskVO.java
- src/main/java/com/mealzo/dto/MQnaVO.java
- src/main/java/com/mealzo/service/MAdminService.java
- src/main/resources/mybatis/mapper/MAdminDao.xml
- src/main/resources/static/admin/script/adminProduct.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/qna/qnaDetil.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qnaList.jsp
> [민지] 어드민 고객관리 완료

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/dao/IMCartDao.java
- src/main/java/com/mealzo/dto/MOrderVO.java
- src/main/java/com/mealzo/service/MCartService.java
- src/main/resources/mybatis/mapper/MCartDao.xml
- src/main/resources/mybatis/mapper/MMemberDao.xml
- src/main/resources/mybatis/mapper/MOrderDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/include/user/mypage_sidemenu.jsp
- src/main/webapp/WEB-INF/views/member/completeWithdrawal.jsp
[한성희] 220404 회원탈퇴 완료, 로그인 일부 오류 수정
> [한성희] 220404 회원탈퇴 완료, 로그인 일부 오류 수정

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/controller/MEventController.java
- src/main/java/com/mealzo/dao/IMEventDao.java
- src/main/java/com/mealzo/dto/MEventVO.java
- src/main/java/com/mealzo/service/MEventService.java
- src/main/resources/mybatis/mapper/MEventDao.xml
- src/main/resources/mybatis/mapper/MNoticeDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/product/productList.jsp
- src/main/webapp/WEB-INF/views/customerCenter/eventDetail.jsp
- src/main/webapp/WEB-INF/views/customerCenter/eventList.jsp
- src/main/webapp/WEB-INF/views/include/user/customerCenter_sidemenu.jsp
[한성희] 220405 유저 - 이벤트, 이벤트디테일 / 어드민 - 상품 활성화 수정중
> [한성희] 220405 유저 - 이벤트, 이벤트디테일 / 어드민 - 상품 활성화 수정중

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/dao/IMNoticeDao.java
- src/main/java/com/mealzo/dto/MNoticeVO.java
- src/main/java/com/mealzo/service/MNoticeService.java
- src/main/resources/mybatis/mapper/MNoticeDao.xml
- src/main/resources/static/admin/script/adminProduct.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminNoticeDetail.jsp
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminNoticeList.jsp
[건희] 1.Admin공지수정폼으로 이동  2.Admin공지수정동작 구현
> [건희] 1.Admin공지수정폼으로 이동  2.Admin공지수정동작 구현

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/dao/IMNoticeDao.java
- src/main/java/com/mealzo/service/MNoticeService.java
- src/main/resources/mybatis/mapper/MNoticeDao.xml
- src/main/resources/static/admin/script/adminProduct.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
> [건희] 1. Admin 공지사항상태변경기능 구현

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/resources/mybatis/mapper/MAdminDao.xml
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminEventDetail.jsp
> [민지] 어드민이벤트 업데이트 완성 날짜 추가 아직 못함

- src/main/resources/static/user/css/meal.css
- src/main/resources/static/user/script/product.js
- src/main/webapp/WEB-INF/views/include/user/headerfooter/header.jsp
- src/main/webapp/WEB-INF/views/index.jsp
1. 마우스 올리면 슬라이더 멈춤. ( out시 재동작)
2. 좌우 버튼 추가.
3. 하단 paging 내비 연동
> [건희] Main 슬라이드 버튼 및 동작 추가

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/MQnaController.java
- src/main/resources/static/user/script/mypage.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/customerCenter/eventList.jsp
- src/main/webapp/WEB-INF/views/qna/pwdcheck.jsp
[한성희] 220407 진행전이벤트 표시추가 / 비회원문의 비밀번호입력 수정중
> [한성희] 220407 진행전이벤트 표시추가 / 비회원문의 비밀번호입력 수정중

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/resources/mybatis/mapper/MAdminDao.xml
- src/main/webapp/WEB-INF/views/index.jsp
[건희] MAdminDao.xml에 eventInsert가 두개 있어서 하나 지움.
> [건희] MAdminDao.xml에 eventInsert가 두개 있어서 하나 지움.

- src/main/java/com/mealzo/controller/MProductController.java
- src/main/java/com/mealzo/dao/IMZzimDao.java
- src/main/java/com/mealzo/service/MZzimService.java
- src/main/resources/mybatis/mapper/MProductDao.xml
- src/main/resources/mybatis/mapper/MZzimDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
- src/main/webapp/WEB-INF/views/sql.sql
> [민지] 찜 갯수 추가

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/controller/MProductController.java
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminEventDetail.jsp
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminEventInsertForm.jsp
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminEventList.jsp
- src/main/webapp/WEB-INF/views/sql.sql
[한성희] 220411 이벤트 날짜수정 / 시간은 미완성
> [한성희] 220411 이벤트 날짜수정 / 시간은 미완성

- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileMainHeader.jsp
- src/main/webapp/WEB-INF/views/mobile/mobileIndex.jsp
[건희] 외부 병합 후 헤더에 사이드바 버튼 추가 (위치조정은 나중에..)
> [건희] 외부 병합 후 헤더에 사이드바 버튼 추가 (위치조정은 나중에..)

- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/resources/static/mobile/css/mobile.css
- src/main/resources/static/mobile/css/sunghee.css
- src/main/resources/static/mobile/script/mobileMember.js
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileHeader.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileLogin.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileViewId.jsp
> [한성희] 220413 로그인수정중

- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileMainHeader.jsp
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/sidemenu.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileCompleteWithdrawal.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileContract.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileFindIdForm.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileFindIdconfirmNumber.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileJoin.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileLogin.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileUpdate.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileViewId.jsp
- src/main/webapp/WEB-INF/views/mobile/mobileIndex.jsp
- src/main/webapp/WEB-INF/views/mobile/mypage/mobileMypage.jsp
[건희] mobileIndex에서 이전 헤더 삭제, 햄버거버튼 헤더위치로 이동
> [건희] mobileIndex에서 이전 헤더 삭제, 햄버거버튼 헤더위치로 이동

- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/mobileIndex.jsp
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderList.jsp
[건희] 1. 모바일 주문리스트 구현 2. 마이페이지 간간히 수정
> [건희] 1. 모바일 주문리스트 구현 2. 마이페이지 간간히 수정

- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/resources/static/mobile/css/mobile.css
- src/main/resources/static/mobile/script/mobileProduct.js
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductDetail.jsp
> [민지] 상품디테일 완료

- src/main/resources/static/mobile/css/mobile.css
> [건희] 프로덕트 카인드 - 이미지 크기 일치시키기

- src/main/java/com/mealzo/controller/MMemberController.java
> [건희] 회원 useyn 수정

- src/main/java/com/mealzo/controller/mobile/MMCartController.java
- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderCancel.jsp
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderCancelDetail.jsp
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderDetail.jsp
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderList.jsp
> [건희] 모바일 주문부분 완료

- src/main/java/com/mealzo/controller/mobile/MMCartController.java
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductDetail.jsp
> [건희] 카트인서트 버그 수정

- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/memberSidemenu.jsp
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/sidemenu.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileContract.jsp
[한성희] 220414 멤버 사이드메뉴, 헤더완료 // 회원탈퇴, 수정 css 남음
> [한성희] 220414 멤버 사이드메뉴, 헤더완료 // 회원탈퇴, 수정 css 남음

- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
- src/main/java/com/mealzo/dao/IMOrderDao.java
- src/main/java/com/mealzo/service/MOrderService.java
- src/main/resources/mybatis/mapper/MOrderDao.xml
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderDetail.jsp
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderList.jsp
> [건희] 1. 주문취소 안되는 것 고침

- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileFooter.jsp
- src/main/webapp/WEB-INF/views/mobile/mobileIndex.jsp
> [건희] 1. 모바일 footer 완성

- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/customerCenter/mobileEventDetail.jsp
- src/main/webapp/WEB-INF/views/mobile/customerCenter/mobileEventList.jsp
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileFooter.jsp
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/sidemenu.jsp
- src/main/webapp/WEB-INF/views/mobile/mypage/mobileMypage.jsp
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductKind.jsp
[건희] 1. 모바일 이벤트 페이지 완성  2. 웹폰트 css 적용
> [건희] 1. 모바일 이벤트 페이지 완성  2. 웹폰트 css 적용

- src/main/java/com/mealzo/controller/mobile/MMQnaController.java
- src/main/resources/static/mobile/script/mobileMypage.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/mobile/qna/mobileNmqnaList.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileNmqnaView.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileNmqnaWrite.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobilePwdcheck.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileQnaList.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileQnaWrite.jsp
[한성희] 220415 비회원/회원 문의관련 오류수정완료 (웹사이트 비회원문의 비밀번호도 버그수정완료)
> [한성희] 220415 비회원/회원 문의관련 오류수정완료 (웹사이트 비회원문의 비밀번호도 버그수정완료)

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminEventInsertForm.jsp
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileMemberHeader.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileNmqnaWrite.jsp
[건희] 1. 이벤트 작성시 시간이 12시로 고정되는 버그 fix
> [건희] 1. 이벤트 작성시 시간이 12시로 고정되는 버그 fix

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/controller/MServiceController.java
- src/main/java/com/mealzo/controller/mobile/MMServiceController.java
- src/main/java/com/mealzo/dao/IMNoticeDao.java
- src/main/java/com/mealzo/service/MNoticeService.java
- src/main/resources/mybatis/mapper/MNoticeDao.xml
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
풀 받고 아래 세개 프로시저 실행해야함.
-- user 공지사항 카운트 getAllCountNotice_m
-- user 공지 조회 getNoticeList_m
-- admin 공지 조회 getNoticeAll_m
> [건희] 1. 공지사항 useyn 체크 안하던 버그 fix ( 프로시저 3개 실행해야함.)

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/java/com/mealzo/controller/mobile/MMQnaController.java
- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/member/login.jsp
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileMemberFooter.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileCompleteWithdrawal.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileContract.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileFindIdForm.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileFindIdconfirmNumber.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileFindZipNum.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileIdcheck.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileJoin.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileLogin.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileUpdate.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileViewId.jsp
- src/main/webapp/WEB-INF/views/mobile/mypage/mobileMypage.jsp
[한성희] 220415 멤버용 푸터 / 회원탈퇴 오류수정완료 / 휴면계정 로그인시 a태그 추가완료 (프로시저2개돌려야함)
> [한성희] 220415 멤버용 푸터 / 회원탈퇴 오류수정완료 / 휴면계정 로그인시 a태그 추가완료 (프로시저2개돌려야함)

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
- src/main/java/com/mealzo/controller/mobile/MMQnaController.java
- src/main/resources/static/user/script/mypage.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/order/orderDetail.jsp
- src/main/webapp/WEB-INF/views/order/orderList.jsp
[건희] 
1. 웹 오더 버그 fix중 
2. 회원탈퇴 시 카트 세션 삭제코드 추가
> [건희] 1. 웹 오더 버그 fix중 / 2. 회원탈퇴 시 카트 세션 삭제코드 추가

- src/main/webapp/WEB-INF/views/cart/cartList.jsp
- src/main/webapp/WEB-INF/views/mobile/cart/mobileCartList.jsp
[건희] 1. 장바구니가 비어있을 경우 텍스트 표시하여 푸터 내리도록 함
> [건희] 1. 장바구니가 비어있을 경우 텍스트 표시하여 푸터 내리도록 함

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/webapp/WEB-INF/views/member/login.jsp
- src/main/webapp/WEB-INF/views/mobile/cart/mobileCartList.jsp
- src/main/webapp/WEB-INF/views/mobile/member/mobileLogin.jsp
[건희] 1. 휴면계정 로그인시 비회원 문의 링크안내문구 위치 수정, 중복메시지 제거
> [건희] 1. 휴면계정 로그인시 비회원 문의 링크안내문구 위치 수정, 중복메시지 제거

- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
- src/main/java/com/mealzo/dao/IMOrderDao.java
- src/main/java/com/mealzo/service/MOrderService.java
- src/main/resources/mybatis/mapper/MOrderDao.xml
- src/main/resources/static/user/script/mypage.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderDetail.jsp
- src/main/webapp/WEB-INF/views/order/orderDetail.jsp
[건희] 1. 웹/모바일 배송시작 상품 주문취소 불가하도록 변경
> [건희] 1. 웹/모바일 배송시작 상품 주문취소 불가하도록 변경

- src/main/webapp/WEB-INF/views/index.jsp
- src/main/webapp/WEB-INF/views/mobile/mobileIndex.jsp
- src/main/webapp/WEB-INF/views/mobile/order/mobileOrderDetail.jsp
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductAll.jsp
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductKind.jsp
- src/main/webapp/WEB-INF/views/product/productAll.jsp
- src/main/webapp/WEB-INF/views/product/productkind.jsp
> [건희] 1. 메인 및 카테고리 제목 이모지 추가

- src/main/java/com/mealzo/controller/MAdminController.java
- src/main/java/com/mealzo/dto/MNoticeVO.java
- src/main/resources/mybatis/mapper/MNoticeDao.xml
- src/main/resources/static/mobile/css/mobile.css
- src/main/resources/static/user/script/product.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminNoticeDetail.jsp
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminNoticeInsert.jsp
- src/main/webapp/WEB-INF/views/admin/customerCenter/adminNoticeList.jsp
- src/main/webapp/WEB-INF/views/customerCenter/noticeList.jsp
- src/main/webapp/WEB-INF/views/mobile/customerCenter/mobileNoticeList.jsp
- src/main/webapp/WEB-INF/views/mobile/mobileIndex.jsp
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductDetail.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
- src/main/webapp/WEB-INF/views/sql.sql
- src/main/webapp/WEB-INF/views/sql1.sql
[민지] 웹프로덕트디테일 수량 , 어드민,모바일, 웹 공지 (필독)완료, 모바일인덱스 사진, 네임 변경
> [민지] 웹프로덕트디테일 수량 , 어드민,모바일, 웹 공지 (필독)완료, 모바일인덱스 사진, 네임 변경

- src/main/resources/static/mobile/css/mobile.css
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/sidemenu.jsp
> [건희] 1. 사이드바 아이콘 배치 스타일 정리

- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/resources/static/user/script/mypage.js
[건희] 1. 주문취소시 oseqArr이 null일때 발생하는 버그 Fix
> [건희] 1. 주문취소시 oseqArr이 null일때 발생하는 버그 Fix

- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
[건희] 1. 모바일에서도 주문 취소시 oseq==null일때 발생하는 버그 fix
> [건희] 1. 모바일에서도 주문 취소시 oseq==null일때 발생하는 버그 fix

- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/java/com/mealzo/dao/IMOrderDao.java
- src/main/java/com/mealzo/service/MOrderService.java
- src/main/resources/mybatis/mapper/MOrderDao.xml
- src/main/resources/static/user/script/product.js
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
- src/main/webapp/WEB-INF/views/mobile/qna/mobileQnaView.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileQnaWrite.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
> [민지]즉시구매완료

- src/main/java/com/mealzo/controller/MCartController.java
- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/java/com/mealzo/controller/MProductController.java
- src/main/java/com/mealzo/controller/MQnaController.java
- src/main/java/com/mealzo/controller/MZzimController.java
- src/main/java/com/mealzo/controller/mobile/MMCartController.java
- src/main/java/com/mealzo/controller/mobile/MMMemberController.java
- src/main/java/com/mealzo/controller/mobile/MMOrderController.java
- src/main/java/com/mealzo/controller/mobile/MMProductController.java
- src/main/java/com/mealzo/controller/mobile/MMZzimController.java
- src/main/resources/static/mobile/script/mobileMypage.js
- src/main/resources/static/user/script/mypage.js
- src/main/webapp/WEB-INF/views/include/user/headerfooter/header.jsp
- src/main/webapp/WEB-INF/views/member/login.jsp
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileMainHeader.jsp
- src/main/webapp/WEB-INF/views/mobile/include/headerfooter/mobileMemberHeader.jsp
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/memberSidemenu.jsp
- src/main/webapp/WEB-INF/views/mobile/include/sidemenu/sidemenu.jsp
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductDetail.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
[건희] 1. 로그인 후 이동하려던 페이지로 이동하는 기능 추가
> [건희] 1. 로그인 후 이동하려던 페이지로 이동하는 기능 추가

- src/main/webapp/WEB-INF/views/member/login.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileNmqnaView.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileNmqnaWrite.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileQnaView.jsp
- src/main/webapp/WEB-INF/views/mobile/qna/mobileQnaWrite.jsp
> [한성희] 220417 별거없습니다~

- src/main/java/com/mealzo/controller/MOrderController.java
- src/main/resources/static/user/script/product.js
[건희] 1. 비회원이 즉시구매 버튼 클릭시 로그인 이후 다시 detail로 이동하는 기능 추가
> [건희] 1. 비회원이 즉시구매 버튼 클릭시 로그인 이후 다시 detail로 이동하는 기능 추가

- src/main/webapp/WEB-INF/views/member/login.jsp
- src/main/webapp/WEB-INF/views/mobile/product/mobileProductDetail.jsp
- src/main/webapp/WEB-INF/views/product/productDetail.jsp
[한성희] 220417 찜하기이후 뒤로가기 눌렀을때 버그 fix
> [한성희] 220417 찜하기이후 뒤로가기 눌렀을때 버그 fix

- src/main/webapp/WEB-INF/views/mobile/product/mobileProductAll.jsp
- src/main/webapp/WEB-INF/views/product/productAll.jsp
[건희] 1. 상품 검색 후, 정렬 버튼 클릭시 검색이 풀리는 버그 fix ( url에서 ' &key=${key } '  추가)
> [건희] 1. 상품 검색 후, 정렬 버튼 클릭시 검색이 풀리는 버그 fix ( url에서 ' &key=${key } '  추가)

- src/main/java/com/mealzo/controller/MMemberController.java
- src/main/webapp/WEB-INF/views/MealzoProcedure.sql
> [민지] 필독 배열 수장 , 로그아웃 세션 remove
